apiVersion: apps/v1
kind: Deployment
metadata:
  name: skaffale
  namespace: skaffale
spec:
  selector:
    matchLabels:
      app: skaffale
  replicas: 1
  template:
    metadata:
      labels:
        app: skaffale
    spec:
      containers:
        - name: skaffale-client
          image: skaffaleclient-image
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /
              port: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
        - name: skaffale-api
          image: skaffaleapi-image
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
        - name: skaffale-database
          image: postgres
          imagePullPolicy: Never
          ports:
            - containerPort: 5432
        - name: adminer
          image: adminer
          imagePullPolicy: Never
          ports:
            - containerPort: 3001