name: Deploy
on:
  push: 
    branches: [ main ]
  release: 
    types:
      - published

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Pull postgres image
        run:
          docker pull postgres

      - name: Pull adminer image
        run:
          docker pull adminer

      - name: Docker Setup Buildx
        id: buildx
        uses: docker/setup-buildx-action@94ab11c41e45d028884a99163086648e898eed25

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/server, 
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/client,

      - name: Build and push Docker image
        uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a
        with:
          context: client
          labels: ${{ steps.meta.outputs.labels }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a
        with:
          context: server
          labels: ${{ steps.meta.outputs.labels }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}

      - name: Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: 'tag:ci'

      - name: Kubernetes context
        uses: Azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }}
          namespace: default

      - name: Apply kube namespace
        run: kubectl apply -f ./k8s/namespace.yaml

      - name: Apply kube secrets
        run: kubectl apply -f ./k8s/secret.yaml

      - name: Apply kube deploy
        run: kubectl apply -f ./k8s/deployment.yaml

      - name: Apply kube service
        run: kubectl apply -f ./k8s/service.yaml
      
      - name: Apply kube ingress
        run: kubectl apply -f ./k8s/ingress.yaml
